source 'https://rubygems.org'
gem 'asciidoctor', '~> 1.5', '>= 1.5.5'
gem 'asciidoctor-diagram', '~> 1.5', '>= 1.5.2'
gem 'asciidoctor-pdf', '~> 1.5.0.alpha.13'
gem 'coderay', '~> 1.1', '>= 1.1.1'

# Fast web serving for results
gem 'puma', '~> 3.6', '>= 3.6.1'
gem 'rack', '~> 1.6', '>= 1.6.5'

# Support build scripts
gem 'rake', '~> 11.2', '>= 11.2.2'
